### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by dwkarjosukarso** [single-cell-genetics/cardelino#6] opened 2020-08-26 17:49 UTC
Hi!
I am really interested in trying this tool, but I had not been able to install it.

I have tried via devtools and get the following error:
Error: Failed to install 'cardelino' from GitHub:
  (converted from warning) dependencies ‘XML’, ‘conquer’, ‘pbkrtest’ are not available

If I try to install the dependencies, I got the following error (same for all three):
Warning in install.packages :
  package ‘conquer’ is not available (for R version 3.5.0)

I tried the singularity (within conda environment, since I am not allowed to install anything on the server outside conda env), but I kept getting the following error:
singularity exec rsc.img R
INFO:    Convert SIF file to sandbox...
FATAL:   while extracting rsc.img: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

I am not familiar with singularity and have tried quite a lot of stuffs from gooling, but cannot get passed this error.

Would you please help me with the installation?
Thank you.

**Comment by davismcc** [comment] 2021-09-21 06:29
Thanks for the bug report. I have just seen installation issues arise with changes apparently in the {rvcheck} package affecting {ggtree} and by extension {cardelino}. I'll look into it and try to get a fix for you ASAP.

**Comment by jeffreypullin** [comment] 2022-06-24 05:28
Hi @dwkarjosukarso, 

Looking at your error messages I suspect that your problem is caused by an issue in your R environment which unfortunately is difficult for us to help with. 

I'm therefore going to close this issue now. If you have further information about your problem or wish to follow up please feel free to reopen it :)

Best, 
Jeffrey

**Closed by jeffreypullin** 2022-06-24 05:28 UTC
